config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :tags, only: [:index, :show, :create, :destroy]
  resources :newest, only: [:index]
  resources :users, only: [:show, :edit, :update]
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :Prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :tags, through: :prototype_tags, dependent: :destroy
  has_many :prototype_tags, dependent: :destroy
  has_many :comments
  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images
  accepts_nested_attributes_for :tags, reject_if: :reject_tags, allow_destroy: true

  has_one :main_image, -> { where(status: 0) }, class_name: "CapturedImage"

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_tags(attributes)
    exists = attributes[:id].present?
    empty = attributes[:name].blank?
    attributes.merge!(_destroy: 1) if exists && empty
    !exists && empty
  end

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  Max_sub_image = 3
  def set_sub_thumbnails
    sub_images = captured_images.sub
    Max_sub_image.times { |i| sub_images[i] ||= captured_images.build(status: "sub") }
    sub_images
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

  def likes_user(user)
    likes.find_by(user_id: user)
  end

  def save_tags(tags)
  current_tags = self.tags.pluck(:name) unless self.tags.nil?
  old_tags = current_tags - tags
  new_tags = tags - current_tags

  # Destroy old taggings:
  old_tags.each do |old_name|
    self.tags.delete Tag.find_by(name:old_name)
  end

  # Create new taggings:
  new_tags.each do |new_name|
    article_tag = Tag.find_or_create_by(name:new_name)
    self.categories << article_tag
  end
  end
end

app/models/prototype_tag.rb
class PrototypeTag < ActiveRecord::Base
  belongs_to :tag
  belongs_to :prototype
  validates :prototype_id,presence:true
  validates :tag_id,presence:true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name,presence:true,length:{maximum:20}
  has_many :prototype, through: :prototype_tags
  has_many :prototype_tags, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :likes
  has_many :comments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @prototypes = Prototype.find(params[:prototype_id])
    if @comment.save
      @comments = @prototypes.comments.length
      @comment.user.avatar
      respond_to do |format|
        format.html { redirect_to prototype_path(params[:prototype_id])  }
        format.json
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(prototype_id: params[:prototype_id], user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
    @id_name = "#like-link-#{@prototype.id}"
@id_heart = "#heart-#{@prototype.id}"
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
    @prototype = Prototype.find(params[:prototype_id])
    @id_name = "#like-link-#{@prototype.id}"
@id_heart = "#heart-#{@prototype.id}"
  end
end

app/controllers/newest_controller.rb
class NewestController < ApplicationController
  def index
    @prototypes = Prototype.order("created_at DESC").page(params[:page]).per(4)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:show, :edit, :update]

  def index
    @prototypes = Prototype.order("created_at ASC").page(params[:page]).per(4)
    @popular = Prototype.order('likes_count DESC').page(params[:page]).per(4)
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
    @tags = Tag.new
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to :root, notice: 'New prototype was successfully created'
    else
      redirect_to ({ action: new }), alert: 'YNew prototype was unsuccessfully created'
    end
  end

  def show
    @likes = Like.where(prototype_id: params[:id])
    @tags = @prototype.tags
    @comments = @prototype.comments
    @comment = Comment.new
  end

  def destroy
    prototype = Prototype.find(params[:id])
    if prototype.user_id = current_user.id
      prototype.destroy
    end
    redirect_to root_path, notice: "削除しました"
  end

  def edit
    @tag_list = @prototype.tags.name
    @captures = @prototype.captured_images
    @sub_images = @prototype.set_sub_thumbnails
    @captures.each do |capture|
      if capture.status == "main"
        @main_image = capture
      end
    end
    return @main_image
  end

  def update
    if @prototype.update(prototype_params)
      redirect_to :root
    else
      render :edit
    end
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:id, :content, :status],
      tags_attributes: [:id, :name, :_destroy]
    )
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag_list = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
  end

  def show
    # binding.pry
    @tag = Tag.find(params[:id])
    @prototypes = Prototype.joins(:tags).includes(:tags).order('tags.name').page(params[:page]).per(4)
  end

  def destroy
  end

  def edit

  end

  def update

  end

  private
  def tag_params
    params.require(:tag_list).permit()
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototype_helper.rb
module PrototypeHelper
  def likes_counter(likes)
    likes.count
  end

  def likes_user(user)
    likes = @likes.find_by(user_id: user)
    return likes
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/likes/_like_links.html.haml
%div.like-link{id: "like-link-#{prototype.id}"}
  - if current_user.likes.find_by(prototype_id: prototype.id)
    = link_to prototype_like_path(prototype_id: prototype.id, id: prototype.id), method: :delete, remote: true do
      .btn.btn-default.heart{id: "heart-#{prototype.id}"}
        = image_tag("icon_red_heart.svg")
        = prototype.likes.count.to_s
  - else
    = link_to prototype_likes_path(prototype_id: prototype.id, id: prototype.id), method: :post, remote: true do
      .btn.btn-default.heart{id: "heart-#{prototype.id}"}
        = image_tag("icon_heart.svg")
        = prototype.likes.count.to_s

app/views/likes/_likes.html.erb
<% if user_signed_in? %>
  <% if prototype.likes_user(current_user.id) %>
    <%= button_to prototype_like_path(like, prototype_id: prototype.id), method: :delete, id: "like-button", remote: true do %>
      <%= image_tag("icon_red_heart.svg") %>
      <span>
        <%= prototype.likes_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to prototype_likes_path(prototype), id: "like-button", remote: true do %>
      <%= image_tag("icon_heart.svg") %>
      <span>
        <%= prototype.likes_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <%= image_tag("icon_heart.svg") %>
    <span>
      <%= prototype.likes_count %>
    </span>
<% end %>

app/views/likes/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", prototype: @prototype, likes: @likes, like: @like )) %>');

app/views/likes/destroy.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", prototype: @prototype, likes: @likes )) %>');

app/views/newest/_prototype_newest.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && prototype.user_id == current_user.id
    .dropdown.drop_menu_location
      %input{ "type" => "button", "id" => "dropdownMenu", "class" => "btn btn-default dropdown-toggle", "value" => "ACTION", "data-toggle" => "dropdown" }
        %ul.dropdown-menu
          %li
            = link_to 'Delete', prototype_path(prototype), method: 'delete'
          %li
            = link_to 'Edit', edit_prototype_path(prototype), method: 'get'
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/newest/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/"
        %li.btn-default.btn-popular
          = link_to "Newest", "newest"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototype_newest', collection: @prototypes, as: :prototype

.text-center
  %ul.pagination
    = paginate(@prototypes)

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && prototype.user_id == current_user.id
    .dropdown.drop_menu_location
      %input{ "type" => "button", "id" => "dropdownMenu", "class" => "btn btn-default dropdown-toggle", "value" => "ACTION", "data-toggle" => "dropdown" }
        %ul.dropdown-menu
          %li
            = link_to 'Delete', prototype_path(prototype), method: 'delete'
          %li
            = link_to 'Edit', edit_prototype_path(prototype), method: 'get'
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"

      .row
        .col-md-12
          %h4 Main Thumbnail
          .fileinput-preview.thumbnail.cover-image-upload#main_image_uploader
            = f.fields_for :captured_images, @main_image do |image|
              -# - binding.pry
              = image_tag image.object.content
              = image.file_field :content
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            = f.fields_for :captured_images, @sub_images do |image|
              %li.list-group-item.col-md-4
                .image-upload
                  = image_tag image.object.content
                  = image.file_field :content
                  = image.hidden_field :status, value: "sub"

      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          .row
            = f.fields_for :tags, @tag_list do |tag|
              .col-md-3
                = tag.text_field :name, placeholder: "Web Design", id:"prototype_tag_0"
                = tag.hidden_field :_destroy
      .row.text-center.proto-btn
        = f.submit "EDIT", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/"
        %li.btn-default.btn-popular
          = link_to "Newest", "newest"
      = link_to "VIEW TAGS", "/tags", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @popular, as: :prototype

.text-center
  %ul.pagination
    = paginate(@popular)

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12.fileinput.fileinput-new
          %h4 Main Thumbnail
          .fileinput-preview.thumbnail.cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload{ class: i }
                  = f.fields_for :captured_images do |image|
                    %img
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          .row
            = f.fields_for :tags, @tags do |tag|
              .col-md-3
                = tag.text_field :name, require: true, placeholder: "Web Design", id:"prototype_tag_0", value: ""
            = f.fields_for :tags, @tags  do |tag|
              .col-md-3
                = tag.text_field :name, placeholder: "UI", id:"prototype_tag_1", value: ""
            = f.fields_for :tags, @tags  do |tag|
              .col-md-3
                = tag.text_field :name, placeholder: "Rails", id:"prototype_tag_2", value: ""
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
    .col-md-6.clearfix
      .likes-box
        = render 'likes/like_links', prototype: @prototype, likes: @likes, like: @like
  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @tags.each do |tag|
          %li
            = link_to tag_path(tag), class: "btn btn-default" do
              = tag.name
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
        = "(#{@comments.length})"
    #comment_area.col-md-8
      #comment_list
        -if @comments
          - @comments.each do |comment|
            .media
              .media-left
                = image_tag(comment.user.avatar)
                = link_to ""
              .media-body
                %h4.media-heading#top-aligned-media= comment.user.name
                %p= comment.text
      = form_for [@prototype,@comment] do |f|
        %h4 Write a comment
        .row
          .form-group.col-md-10
            = f.text_area :text
          .form-group.col-md-2
            = f.submit "COMMENT", class: "comment-submit"

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default.navbar-btn
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2
        Tag List
      %ul
        - @tag_list.each do |tag|
          %li.col-md-4
            = link_to "#{tag.name}", tag_path(tag), class: "btn btn-default"

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "/"
        %li.btn-default.btn-popular
          = link_to "Newest", "/newest"
      = link_to "VIEW TAGS", "/tags", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    .tag-show
      .tag-show__tagbox
        = link_to @tag.name, "/tags/#{@tag.id}"

    = render partial: 'prototypes/prototype', collection: @prototypes, as: :prototype

.text-center
  -# %ul.pagination
  -#   = paginate(@prototypes)

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes